[versions]
lottieCompose = "6.6.7"
timber = "5.0.1"

[libraries]
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieCompose" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }